---
title: "questions"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{questions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Réu 20210610 P. Mercé

## Questions

Parkings "St Jean" -> OK

---

Taux occupations négatifs -> voir pour rajouter un onglet qualité de données avec les données incohérentes
Nb de fois par jour où on a libres > total

---

"En donnant aux destinataires la possibilité de cocher la temporalité du reporting: à la semaine, au mois, trimestre, année"
C'est l'axe des x qui va etre impacté; ex si sélection au mois, les données sont journalières ? avec la moyenne sur la journée ?
Si c'est au trimestre c'est quoi ?


Occupation : nom du parking dans la légende plutot que l'identifiant
Style de ligne différent pour la moyenne (plus gros par ex)
Menu pour sélectionner uniquement un sous ensemble de pkgs à afficher

Cache jour (8h-20h) / nuit (20-8h) / ou plage horaire au choix
--> Pour le moment possible uniquement si on choisit les données à la maille horaire

Calendrier s'adapte à la temporalité choisie par l'utilisateur.

-----
Si on sélectionne une journée : on affiche à l'heure ?
Journée resittuée à la maille horaire

Si on sélectionne une semaine : axe des x : jour

Si on sélectionne un mois : axe des x : jour

Si on selectionne une année : axe des x : mois
----
Pour la saturation, on autorise que la sélection d'une semaine ? si sélection supérieur à 1 semaine on propose la sélection d'une semaine donnée via un sélecteur ?

Au max sélection d'un mois, on garde un parking si le critère est rempli pour 1 semaine au moins
Voir pour inverser les axes du graphique


# Réu 01/07/21 P. Mercé P. Brebinaud

## Questions

Cache jour (8h-20h) / nuit (20-8h) / ou plage horaire au choix
--> Pour le moment possible uniquement si on choisit les données à la maille horaire

Proposer de mettre 2 graphes coté à coté pour la saturation avec 2 petits sélecteurs

Utilise t on le même système avec 2 graphes pour la comparaison année précédente ?
Comment on fait pour une journée ou une semaine 1 an avant ? 
Pour la semaine on peut proposer de prendre le même numéro de semaine

Partie qualité de données : rapport à la semaine par ex ...

## Réponses

Occupation : proposer 2 options moyenne des parkings de la zone / moyenne des parcs sélctionnés uniquement 
Comparaison : manuellement pour pas de temps jour et semaine
en dur pour mois et année

Modifier panneau pour avoir des critères manuels pour la saturation




